export default function Page() {
  return (
    <main style={{minHeight:'100vh',display:'flex',flexDirection:'column',alignItems:'center',justifyContent:'center',background:'linear-gradient(180deg,#0A0A0A 0%,#111 100%)',color:'#fff',fontFamily:'system-ui,sans-serif',padding:'2rem',textAlign:'center'}}>
      <h1 style={{fontSize:'3rem',fontWeight:700,letterSpacing:'-0.04em',marginBottom:'1rem'}}>ai-app</h1>
      <p style={{maxWidth:'40rem',opacity:0.7,lineHeight:1.6}}>Generated project</p>
      <p style={{marginTop:'2rem',fontSize:'0.85rem',opacity:0.4}}>Generated by Forge.ai — deployed via GitHub + Vercel</p>
    </main>
  );
}
